name: Java CI with Maven

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Environment Variables
      run: |
        echo "URL=$URL" > $GITHUB_WORKSPACE/.env
        echo "USER_NAME=$USER_NAME" >> $GITHUB_WORKSPACE/.env
        echo "PASSWORD=$PASSWORD" >> $GITHUB_WORKSPACE/.env
        echo "ACCESS_KEY=$ACCESS_KEY" >> $GITHUB_WORKSPACE/.env
        echo "SECRET_KEY=$SECRET_KEY" >> $GITHUB_WORKSPACE/.env
        echo "URL_TEST=$URL_TEST" >> $GITHUB_WORKSPACE/.env
        echo "USER_NAME_TEST=$USER_NAME_TEST" >> $GITHUB_WORKSPACE/.env
        echo "PASSWORD_TEST=$PASSWORD_TEST" >> $GITHUB_WORKSPACE/.env
      env:
        URL: ${{ secrets.URL }}
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        URL_TEST: ${{ secrets.URL_TEST }}
        USER_NAME_TEST: ${{ secrets.USER_NAME_TEST }}
        PASSWORD_TEST: ${{ secrets.PASSWORD_TEST }}

    - uses: actions/checkout@v2

    - name: Set up JDK 20.0.2
      uses: actions/setup-java@v2
      with:
        java-version: '20.0.2'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 20.0.2
      uses: actions/setup-java@v2
      with:
        java-version: '20.0.2'
        distribution: 'temurin'

    - name: Configure Test Environment
      run: |
        mv $GITHUB_WORKSPACE/.env src/test/resources/.env
      shell: bash

    - name: Test with Maven
      run: mvn test
